### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by 10kkm** [NIKDISSV-Forever/HDRezka#1]
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/anipj/main.py", line 52, in main
    stream = await ani.get_stream(g, h, translats[b-1][1])
  File "/usr/local/lib/python3.10/dist-packages/hdrezka/stream/player.py", line 77, in get_stream
    return urls_from_ajax_response(
  File "/usr/local/lib/python3.10/dist-packages/hdrezka/post/urls/urls.py", line 12, in urls_from_ajax_response
    return URLs(VideoURLs(response.get('url', '')),
  File "/usr/local/lib/python3.10/dist-packages/hdrezka/post/urls/kind/video.py", line 24, in __init__
    self.qualities: tuple[Quality] = *sorted(self.raw_data),
TypeError: 'bool' object is not iterable

on windows its working well, but when im trying on my vps its throwing this error

**Comment by ndenissov** [comment]
I failed to reproduce this error, could you please provide me with the get_stream arguments at which this error occurs and any other information that will help reproduce the error (package version, part of your source code, startup parameters, system or something else) I used VCL if it matters.

**Comment by ndenissov** [comment]
https://github.com/NIKDISSV-Forever/HDRezka/commit/f24deb9769d126a166a8f709936305493770154a It'll now raise `TypeError`, since pass the `bool` isn't the correct behavior.

**Comment by 10kkm** [comment]
its the first try on linux with pm2 and venv, python 3.10, this error appears for any get stream. And i saw another error about dictionary changed 
File "G:\anipj\venv\lib\site-packages\hdrezka\stream\player.py", line 25, in set
    for k in self.__storage.keys():
    so i fixed it with tuple(self.__storage.keys())

**Comment by ndenissov** [comment]
> its the first try on linux with pm2 and venv, python 3.10, this error appears for any get stream. And i saw another error about dictionary changed File "G:\anipj\venv\lib\site-packages\hdrezka\stream\player.py", line 25, in set for k in self.__storage.keys(): so i fixed it with tuple(self.__storage.keys())

fixed at https://github.com/NIKDISSV-Forever/HDRezka/commit/c1d4d4455c31a38b885a3a1affc98b9de0945ff2


Upgrade to `3.0.3` and check the functionality, if there are no more problems, the issue can be closed.

**Comment by 10kkm** [comment]
Fixed, thank u!

**Comment by 10kkm** [comment]
TypeError: got False (type <class 'bool'>) but expected type str | dict
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/root/anipj/main.py", line 154, in buttons_callback
    print(f"{await pl.get_stream(seas, epi, trans)}")
  File "/usr/local/lib/python3.10/dist-packages/hdrezka/stream/player.py", line 76, in get_stream
    return urls_from_ajax_response(
  File "/usr/local/lib/python3.10/dist-packages/hdrezka/post/urls/urls.py", line 12, in urls_from_ajax_response
    return URLs(VideoURLs(response.get('url', '')),
  File "/usr/local/lib/python3.10/dist-packages/hdrezka/post/urls/kind/video.py", line 27, in __init__
    raise TypeError(f'got {data!r} (type {type(data)}) but expected type {str | dict}')
TypeError: got False (type <class 'bool'>) but expected type str | dict

**Comment by 10kkm** [comment]
any chance to fix this?

**Comment by ndenissov** [comment]
Сould you send the series season and episode on which this error occurs, or does it occur everywhere?
So far, I can't say what this is related to.

**Comment by 10kkm** [comment]
it occurs with any

**Comment by ndenissov** [comment]
I haven't any ideas at the moment...

**Comment by 10kkm** [comment]
its okay i can just use windows server

**Comment by 10kkm** [comment]
nah these windows servers are expensive, we need to fix that 💀

**Comment by ndenissov** [comment]
Since I don't get the same behavior, maybe for example you have redefined the `sorted` function somewhere so that it returns a `bool`? I'll check everything again, but maybe the problem occurs in your environment

**Comment by 10kkm** [comment]
nah, everything is OK, i launch it with pm2 and python3.10 by path /usr/bin/python3.10
i tried with and without env, can we go to discord or telegram and discuss it? Cuz here its not so fast, then we'll write here if its solved

**Comment by 10kkm** [comment]
receive_response_headers.complete return_value=(b'HTTP/1.1', 301, b'Moved Permanently',
INFO HTTP Request: GET https://rezka.ag/52222-52222.html "HTTP/1.1 301 Moved Permanently"
huh

**Comment by 10kkm** [comment]
oh this error with bool appears in other libs, ig its cuz of 301 moved perm

**Comment by ndenissov** [comment]
I doubt that this is because of 301, there is a check in the code that this is a redirect (301, 302)

**Comment by 10kkm** [comment]
lol, i get this bool on windows server too. latest 3.11, 2012 r2. On local pc i dont get this error, nice

**Comment by 10kkm** [comment]
hey there, some sites are blocked, will this lib support proxy???

**Comment by ndenissov** [comment]
Fixed https://github.com/NIKDISSV-Forever/HDRezka/commit/af16c0f4cbe28ec75f80da077554aa4c89e76327. Update to version 3.2.0.

**Comment by 10kkm** [comment]
TypeError: got False (type <class 'bool'>) but expected type str | dict
Traceback (most recent call last):
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
  File "/root/anipj/gay/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/root/anipj/main.py", line 215, in buttons_callback
    stream = await pl.get_stream(seas, epi, trans)
  File "/root/anipj/gay/lib/python3.10/site-packages/hdrezka/stream/player.py", line 88, in get_stream
    return urls_from_ajax_response(
  File "/root/anipj/gay/lib/python3.10/site-packages/hdrezka/post/urls/urls.py", line 17, in urls_from_ajax_response
    return URLs(VideoURLs(response.get('url', '')),
  File "/root/anipj/gay/lib/python3.10/site-packages/hdrezka/post/urls/kind/video.py", line 37, in __init__
    raise TypeError(f'got {data!r} (type {type(data)}) but expected type {str | dict}')
TypeError: got False (type <class 'bool'>) but expected type str | dict

didnt help 3.2.0

**Comment by ndenissov** [comment]
I really don't understand, maybe if you tell me which series (values of `pl`, `seas`, `epi`, `trans` variables on error) this happens on, I can handle this case properly.
Because, as far as I understand, the `url` field from the API response cannot be bool under any circumstances, but this happens to you.

**Comment by 10kkm** [comment]
do u have discord??

**Comment by ndenissov** [comment]
nikdissv#4299

**Comment by 10kkm** [comment]
will u accept the friend request?

**Comment by Gokujo** [comment]
same issue:
```Python3
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Development\Python\Projects\rezkaMovie\main.py", line 13, in main
    stream = await player.get_stream(1, 1, translator_id)  # raise AJAXFail if invalid episode or translator
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Development\Python\Projects\rezkaMovie\.venv311\Lib\site-packages\hdrezka\stream\player.py", line 88, in get_stream
    return urls_from_ajax_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Development\Python\Projects\rezkaMovie\.venv311\Lib\site-packages\hdrezka\post\urls\urls.py", line 17, in urls_from_ajax_response
    return URLs(VideoURLs(response.get('url', '')),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Development\Python\Projects\rezkaMovie\.venv311\Lib\site-packages\hdrezka\post\urls\kind\video.py", line 43, in __init__
    raise TypeError(f'got {data!r} (type {type(data)}) but expected type {str | dict}')
TypeError: got False (type <class 'bool'>) but expected type str | dict

```

i switched to python 3.11

thos vars are given
![image](https://github.com/NIKDISSV-Forever/HDRezka/assets/19776684/bf591a8e-d2f5-426d-9b01-c547296ea2ad)

**Comment by ndenissov** [comment]
> same issue:
> 
> ```python
> Traceback (most recent call last):
>   File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "D:\Development\Python\Projects\rezkaMovie\main.py", line 13, in main
>     stream = await player.get_stream(1, 1, translator_id)  # raise AJAXFail if invalid episode or translator
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Development\Python\Projects\rezkaMovie\.venv311\Lib\site-packages\hdrezka\stream\player.py", line 88, in get_stream
>     return urls_from_ajax_response(
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Development\Python\Projects\rezkaMovie\.venv311\Lib\site-packages\hdrezka\post\urls\urls.py", line 17, in urls_from_ajax_response
>     return URLs(VideoURLs(response.get('url', '')),
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Development\Python\Projects\rezkaMovie\.venv311\Lib\site-packages\hdrezka\post\urls\kind\video.py", line 43, in __init__
>     raise TypeError(f'got {data!r} (type {type(data)}) but expected type {str | dict}')
> TypeError: got False (type <class ) but     dict
> ```
> 
> i switched to python 3.11
> 
> thos vars are given ![image](https://private-user-images.githubusercontent.com/19776684/304348319-bf591a8e-d2f5-426d-9b01-c547296ea2ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDI0ODgsIm5iZiI6MTcwNzkwMjE4OCwicGF0aCI6Ii8xOTc3NjY4NC8zMDQzNDgzMTktYmY1OTFhOGUtZDJmNS00MjZkLTliMDEtYzU0NzI5NmVhMmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA5MTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5OTRmMWYyNWE5M2FhNTdjOTdlZmRlMDExMTZkODI5N2M2YmQ3OWUxYjc1NzU0YzIwNjJlOWM1ZGMxMTIyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F7BaJ_CZXgeb_i3_a5Fvax7_FZm1U_iUp0JzDgmEg6M)

---

The latest theory was that `False` is returned in the `'url'` field if there are no valid urls for this stream. That's probably why, with all my attempts, I couldn't repeat this error (from Kazakhstan). I can only try to advise you to send requests from a proxy (https://github.com/NIKDISSV-Forever/HDRezka/issues/3) or VPN, and tell me later if you succeeded.
Also make sure that you have access to the stream through the browser.

**Comment by 10kkm** [comment]
Hey! 3.2.3 really helped a lot, I changed link to unofficial rezka and it works now. Thanks

**Comment by ndenissov** [comment]
I'm glad that helped. Let's stick with the version that uses geolocation-based blocking. In this case, you can freely switch hosts to functional mirrors as needed. I will also monitor the default link's availability whenever possible.
