### ISSUE TITLE
short url

### ISSUE THREAD

**Issue by 10kkm** [NIKDISSV-Forever/HDRezka#4]
NameError: name 'short_url' is not defined
Traceback (most recent call last):
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 23, in __call__
    return await handler(event, data)
  File "G:\anipj\venv\lib\site-packages\aiogram\fsm\middleware.py", line 39, in __call__
    return await handler(event, data)
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
  File "G:\anipj\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
  File "G:\anipj\gay.py", line 128, in buttons_callback
    print(data)
  File "G:\anipj\venv\lib\site-packages\hdrezka\stream\player.py", line 55, in __repr__
    return f"{self.__class__.__qualname__}({short_url(self.post.url)!r})"
NameError: name 'short_url' is not defined

**Comment by ndenissov** [comment]
Fixed https://github.com/NIKDISSV-Forever/HDRezka/commit/af16c0f4cbe28ec75f80da077554aa4c89e76327. Update to version 3.2.0.
