### ISSUE TITLE
Здравствуйте, хотел бы попросить вас проконсультировать по поводу вашего api для hdrezka. Я написал телеграм бота для скачивания фильмов с резки и проект нормально работает на моем пк, но если залить бота на сервер не зависимо от системы и интерпретатора, происходит ошибка с методом getStream.

### ISSUE THREAD

**Issue by morrik-tim** [NIKDISSV-Forever/HDRezka#8]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot-master\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot-master\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot-master\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot-master\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot-master\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot-master\optimus.py", line 96, in translator_callback_handler
    await process_film()
  File "C:\Users\Administrator\Desktop\bot-master\optimus.py", line 208, in process_film
    stream = await player.get_stream(translator_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot-master\venv\Lib\site-packages\hdrezka\stream\player.py", line 71, in get_stream
    return urls_from_ajax_response(await AJAX.get_movie(self.post.id, self._translator(translator_id)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot-master\venv\Lib\site-packages\hdrezka\post\urls\urls.py", line 17, in urls_from_ajax_response
    return URLs(VideoURLs(response.get('url', '')),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot-master\venv\Lib\site-packages\hdrezka\post\urls\kind\video.py", line 43, in __init__
    raise TypeError(f'got {data!r} (type {type(data)}) but expected type {str | dict}')
TypeError: got False (type <class 'bool'>) but expected type str | dict

**Comment by ndenissov** [comment]
Это известная проблема https://github.com/NIKDISSV-Forever/HDRezka/issues/1 (ответьте в этой теме, если будут новости)
Ошибка возникает если hdrezka блокирует доступ из вашего местоположения (в плеере при этой ошибке вылазит большая красная надпись "контент недоступен в вашем регионе", или как-то так)
Так что, если это возможно, попробуйте поднять бота в той же стране что и Вы; дайте знать, если и это не решит проблему, вероятнее всего Вы просто сталкиваетесь с блокировкой по ip.
